language: python
python:
  - "3.6"
cache: pip3

install:
  - pip3 install -r requirements.txt
- pip install coveralls
script:
    - nosetests --with-coverage --cover-tests --cover-package=api/tests 
    - coverage report
after_success:
- coveralls